name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Show env
        run: |
          python -V
          pip -V
          ls -la

      - name: Install deps
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Import check
        run: |
          python -c "import gmail_sender; print('gmail_sender import OK')"

      - name: Smoke compile
        run: |
          python -m compileall -q .
